services:
  postgres:
    image: postgres:16
    container_name: 3d2y-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: eliel
      POSTGRES_PASSWORD: eliel123
      POSTGRES_DB: 3d2y_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: